config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"
  devise_for :users, controllers: { omniauth_callbacks: :callbacks }

  resources :likes, only: %i[create]
  resources :tweets
  resources :users

  # customs routes
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  get "/profile", to: "users#edit"
  patch "/profile", to: "users#update"
  post "/profile", to: "users#create"
  get "/profile", to: "users#show"

    # Omniauth
    # get "/auth/github/callback", to: "sessions#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet, counter_cache: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :likes, dependent: :destroy, inverse_of: "tweet"
  belongs_to :replied_to, class_name: "Tweet", optional: true, counter_cache: :replies_count
  has_many :replies, class_name: "Tweet",
                                    foreign_key: "replied_to_id",
                                    dependent: :nullify,
                                    inverse_of: "replied_to"
   # Validates
  validates :body, presence: true, length: { maximum: 140 }
  validates :image, presence: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
	has_one_attached :avatar

	#Associations
	has_many :tweets, dependent: :destroy
    has_many :likes, dependent: :destroy, inverse_of: "user"
    has_many :liked_tweets, through: :likes, source: :tweet
	# Validations
	validates :username, presence: true, uniqueness: true
	# validate :name, presence: true
	validates :avatar, presence: false
	#   has_secure_password
	enum role: { admin: 0,
    user: 1 }

	def self.from_omniauth(auth_hash)
		where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create do |user|
		  user.provider = auth_hash.provider
		  user.uid = auth_hash.uid
		  user.username = auth_hash.info.nickname
		  user.email = auth_hash.info.email
		  user.password = Devise.friendly_token[0, 20]
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_before_action :verify_authenticity_token, :only => [:create]
	before_action :authenticate_user!, except: %i[index show]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :avatar])
		devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :avatar])
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
      auth_hash = request.env["omniauth.auth"]
      @user = User.from_omniauth(auth_hash)
      sign_in_and_redirect(@user)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  # POST /likes
  def create
    @like = Like.new(like_params)
    @like.user = current_user

    if @like.save
        redirect_to(request.referrer || root_path )
    else
        like_to_remove = Like.where(user_id: @like.user_id, tweet_id: @like.tweet_id)
        unless like_to_remove.empty?
            like_to_remove[0].destroy
        end
        redirect_to(request.referrer || root_path )
    end
  end

  private

    def like_params
      params.require(:like).permit(:tweet_id)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets
  def index
    @tweet_new = Tweet.new
    @like_new = Like.new
    @tweets = Tweet.all
    # @user_tweets = policy_scope( Tweet )
    @user_likes = current_user ? current_user.liked_tweets : []
  end

  # GET /tweets/1
  def show
    @tweet_new = Tweet.new
    @like_new = Like.new
    # @user_tweets =  policy_scope( Tweet )
    @user_likes = current_user ? current_user.liked_tweets : []
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      if params[:tweet][:replied_to_id].empty? # Si no hay un replied hablamos de un tweet
        redirect_to tweets_path, notice: "Tweet was successfully created."
      else
        redirect_to @tweet.replied_to, notice: "Retweet was successfully created"
      end
    else
      if params[:tweet][:replied_to_id].empty? # Si no hay un replied hablamos de un tweet
        redirect_to tweets_path, notice: "Cannot tweet"
      else
        redirect_to @tweet.replied_to, notice: "Cannot retweet"
      end
    end
  end

  # PATCH/PUT /tweets/1
  def update
    # @tweet by default
    # authorize @tweet
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: "Tweet was successfully updated."
    else
      redirect_to @tweet, notice: "Tweet cannot be updated."
      # render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @parent_tweet = @tweet.replied_to
    @tweet.destroy
    if @parent_tweet.nil?
      redirect_to tweets_url, notice: "Tweet was successfully destroyed."
    else
      redirect_to @parent_tweet, notice: "Retweet was successfully destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :replies_count, :likes_count, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @like_new = Like.new
    @user = User.find(params[:id])
    # @user_tweets = policy_scope( Tweet )
    @user_likes = current_user ? current_user.liked_tweets : []
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if params.has_key?(:id)
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user, notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    # authorize @user

    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :username, :name, :password, :role, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <p>© 2022 - Codeable Tweetable</p>
    <p>Build with ❤ by</p>
    <div class="footer-content">
        <div class="footer-content__dev">
        <a href="https://github.com/SebastianTerleira" target="_blank">
            <%= image_tag "icons/github.svg"%>
            </a>
            <p>Sebastian Terleira</p>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
 <header class="header">
      <!-- bg gray -->
      <div class="container-lg">
        <nav class="navbar">
          <input type="checkbox" id="menu-mobile" />

          <a href="/#" class="text-decoration-none header--menu-mobile">
            <%= image_tag "icons/logo.png" %>
          </a>

            <!-- option 1 -->
            <label for="menu-mobile" id="toggle-close">
              <i class="ri-close-fill ri-xl"></i>
            </label>

            <!-- option 2 -->
            <label for="menu-mobile" id="toggle-open">
              <i class="ri-menu-line ri-xl"></i>
            </label>

            
          <ul class="expandable navbar--links list-style-none">
            <% if user_signed_in? %>
                <div>
                   <%= link_to "Profile", @user, class: "link text-sm"%>
                </div>
                <div>
                    <%= button_to "Logout", destroy_user_session_path, class: "text-decoration-none button button--xs button--secondary", method: :delete, data: { turbo: false } %>
                </div>
            <% else %>
                <div>
                    <%= link_to "Login", new_user_session_path,  class: "button text-decoration-none button--primary" %>
                </div>
            <% end %>
          </ul>

        </nav>
      </div>   
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="body">
    <%= render "layouts/header" %>
    <div class="body-content">
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/tweets/_comment.html.erb
<div>
    <%= form_with url: tweets_path, model: tweet_new do |form| %>
        <div class="tweet-new">
            <%= form.text_area :body, placeholder: "Remember to thing before write...", rows: 3, class: "tweet-body"%>
            <% if !parent_tweet.nil? %>
                <%= form.hidden_field :replied_to_id, value: parent_tweet.id %>
            <% else %>
                <%= form.hidden_field :replied_to_id, value: nil %>
            <% end %>
            <%= form.submit "Tweet", class: "button button--primary overline"%>
        </div>   
    <% end %>
<div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <div class="tweet-new">
    <% if tweet.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
          <% tweet.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <%= form.text_area :body, placeholder: "Remember to thing before write...", rows: 3, class: "tweet-body w-full"%>
      <%= form.submit "Update", class: "button button--primary overline"%>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="tweet-card">
  <div class="tweet-card__header"> <!-- Header -->
    <div class="user-avatar">
      <% if tweet.user.avatar.attached? %>
        <%= image_tag tweet.user.avatar %>
      <% else %>
        <%=  image_tag "user/default_user.jpg"%>
      <% end %>
    </div>
    <%= link_to tweet.user, class: "text-decoration-none gray-900" do%>
      <div class="mx-0.25">
        <div class="flex gap-0.25">
          <h2 class="font-primary bold text-md"><%= tweet.user.name%></h2>
          <h2 class="font-primary regular text-md pink-600">@<%= tweet.user.username%></h2>
        </div>
         <p class="font-primary regular text-sm gray-500"><%= time_ago_in_words(tweet.created_at)%> ago</p>
      </div>
    <% end %>
  </div>
  <%= link_to tweet, class: "text-decoration-none gray-900" do %>
    <div class="tweet-card__body"> <!-- Body -->
        <p class="font-primary regular text-md"><%= tweet.body %></p>
    </div>
  <% end %>
  <div class="tweet-card__footer"> <!--Footer -->
    
    <div class="tweet-card__footer-buttons1"> <!-- First two buttons -->
      <%# <% if user_tweets.include?(tweet) %>
        <%= button_to tweet, method: :delete, class: "button-cleaned" do %>
          <%= image_tag "icons/erase.png" %>
        <%# <% end %>
        <%= button_to  edit_tweet_path(tweet), method: :get, class: "button-cleaned" do %>
          <%= image_tag "icons/edit.png" %>
        <% end %>
      <% end %>
    </div>

    <div class="tweet-card__footer-buttons2"> <!-- Last two buttons -->
      
      <%= link_to tweet do %>
        <%= image_tag "icons/retweet.png" %>
      <% end %>
      <p><%= tweet.replies_count %></p>

      <%= form_with url: likes_path, model: like_new do |form| %>
        <%= form.hidden_field :tweet_id, value: tweet.id %>
        
        <%if user_likes.include?(tweet) %>
          <%= image_submit_tag "icons/liked.png" %>
        <% else %>
          <%= image_submit_tag "icons/like.png" %>
        <% end %>
      <% end %>
      <p><%= tweet.likes_count %></p>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<section class="section-sm">
  <div class="container-sm">
    <div class="w-full center mb-1">
      <h1 class="semibold head-sm">Editing tweet</h1>
    </div>
    
    <div>
      <%= render "form", tweet: @tweet %>
    </div>

    <br>

    <div>
      <%= link_to "Show this tweet", @tweet %> |
      <%= link_to "Back to tweets", tweets_path %>
    </div>

  </div>
</section>

app/views/tweets/index.html.erb
<section class="section-sm">
  <div class="container-sm">
    <p style="color: green"><%= notice %></p>
    <div class="w-full center mb-1">
      <h1 class="semibold head-sm">Home</h1>
    </div>

    <% if  current_user %>
      <div>
        <%= render "comment", tweet_new: @tweet_new, parent_tweet: nil %>
      </div>
    <% end %>

    <div>
      <% @tweets.sort.reverse.each do |tweet| %>
        <% if tweet.replied_to.nil? %>
          <%= render tweet, like_new: @like_new, user_tweets: @user_tweets, user_likes: @user_likes %>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<section class="section-sm">
  <div class="container-sm">
    <p style="color: green"><%= notice %></p>
    <%= render @tweet, like_new: @like_new, user_tweets: @user_tweets, user_likes: @user_likes %>

    <hr class="for-retweets">

    <% if current_user %>
      <div>
        <%= render "comment", tweet_new: @tweet_new, parent_tweet: @tweet %>
      </div>
    <% end %>

    <div>
      <% @tweet.replies.each do |retweet| %>
        <%= render retweet, like_new: @like_new, user_tweets: @user_tweets, user_likes: @user_likes %>
      <% end %>
    </div>
  </div>
</section>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.number_field :role %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_with(model: user) do |form| %>
  <div class="user--form">
    <% if user.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-1">
        <div>
          <%= form.label :username, class:"text-xs overline block"%>
          <%= form.text_field :username, class: "input", placeholder: "example" %>
        </div>
        <% if user.errors.messages[:username].any? %>
          <span class="content-sm input__error-message block">
            <%= user.errors.messages[:username].join(", ")%>
          </span>
        <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :email, class:"text-xs overline block"%>
        <%= form.email_field :email, class: "input", placeholder: "example@gamil.com" %>
      </div>
      <% if user.errors.messages[:email].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:email].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :name, class:"text-xs overline"%>
        <%= form.text_field :name, class: "input", placeholder: "Example Name" %>
      </div>
      <% if user.errors.messages[:name].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:name].join(", ")%>
        </span>
      <% end %>
    </div>

     <div class="mb-1">
      <div class="user-main-image">
          <% if user.avatar.attached? %>
            <%= image_tag user.avatar %>
          <% else %>
            <%= image_tag "user/default_user.jpg"%>
          <% end %>
      </div>
      <div>
        <%= form.label :avatar, class:"text-xs overline"%>
        <%= form.file_field :avatar, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:avatar].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:avatar].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :password, class:"text-xs overline"%>
        <%= form.password_field :password, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:password].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:password].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :password_confirmation, class: "text-xs overline"%>
        <%= form.password_field :password_confirmation, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:password_confirmation].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:password_confirmation].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="mb-1">
      <div>
        <%= form.label :current_password, class:"text-xs overline"%>
        <%= form.password_field :password_confirmation, class: "input", placeholder: "**********" %>
      </div>
      <% if user.errors.messages[:password_confirmation].any? %>
        <span class="content-sm input__error-message block">
          <%= user.errors.messages[:password_confirmation].join(", ")%>
        </span>
      <% end %>
    </div>

    <div class="w-full">
      <%= form.submit "UPDATE", class: "w-full button button--primary" %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div>
  <div class="w-full center mb-1">
    <h1 class="semibold head-sm">Profile<h1>
  </div>

  <div class="user-main-image">
    <% if user.avatar.attached? %>
      <%= image_tag user.avatar%>
    <% else %>
      <%= image_tag "user/default_user.jpg"%>
    <% end %>
  </div>
  <div class="w-full center mb-1.5">
    <h2 class="semibold head-xs mb-0.25"><%= user.name %></h2>
    <p class="font-primary regular text-md gray-500 mb-0.25"><%= user.username %><p>
    <p class="font-primary regular text-md gray-500 mb-1"><%= user.created_at.strftime("Joined on %B %d, %Y") %></p>
    <% if current_user and (current_user.admin? or  current_user == user) %>
      <div class="flex justify-center">
        <%= link_to "Edit Profile", edit_user_path(user), class: "button user-button-create button--primary"%>
      </div>
    <% end %>
  </div>

  <input type="radio" id="c-tweets" name="selection" checked/>
  <input type="radio" id="c-liked-tweets" name="selection"/>

  <div class="tabs">
    <div class="tabs-element-tweets">
      <label for="c-tweets" id="toggle-tweets">
        <h3 class="font-primary regular text-md">Tweets (<%= user.tweets.length%>)</h3>
      </label>
    </div>
    <div class="tabs-element-liked-tweets">
      <label for="c-liked-tweets" id="toggle-liked-tweets">
        <h3 class="font-primary regular text-md">Likes (<%= user.liked_tweets.length%>)</h3>
      </label>
    </div>
  </div>
  <!-- User tweets -->
  <div class="expandable-tweets">
    <% user.tweets.each do |tweet| %>
      <%= render "/tweets/tweet", tweet: tweet, like_new: like_new, user_tweets: user_tweets, user_likes: user_likes %>
      <% end %>
  </div>
  <!-- User liked tweets -->
  <div class="expandable-liked-tweets">
    <% user.liked_tweets.each do |tweet|%>
      <%= render "/tweets/tweet", tweet: tweet, like_new: like_new, user_tweets: user_tweets, user_likes: user_likes %>
    <% end %>
  </div>

</div>

app/views/users/edit.html.erb
<section class="section-sm">
  <div class="container-sm">
    <div class="w-full center mb-1">
      <h1>Edit Profile</h1>
    </div>
  </div>

<div class="container-sm">
      <%= render "form_edit", user: @user %>
  </div>
</section>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<section class="section-sm">
  <div class="container-sm">
    <div class="w-full center mb-1">
      <h1>Create an account</h1>
    </div>
  </div>

  <div class="container-sm">
    <%= render "form", user: @user %>
  </div>
</section>

app/views/users/show.html.erb
<section class="section-sm">
  <div class="container-sm">
    <p style="color: green"><%= notice %></p>
    <%= render @user, like_new: @like_new, user_tweets: @user_tweets, user_likes: @user_likes %>
  </div>
</section>